# Generated by Django 3.0.7 on 2020-06-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('like', models.PositiveIntegerField(default=0)),
                ('unlike', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostUserReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('unlike', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'verbose_name': 'PostUserReaction',
                'verbose_name_plural': 'PostUserReactions',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(related_name='post_reactions', to='posts.PostUserReaction'),
        ),
        migrations.AddIndex(
            model_name='postuserreaction',
            index=models.Index(fields=['owner', 'post'], name='posts_postu_owner_i_9f9204_idx'),
        ),
        migrations.AddIndex(
            model_name='postuserreaction',
            index=models.Index(fields=['owner', 'post', 'like'], name='posts_postu_owner_i_cb4208_idx'),
        ),
        migrations.AddIndex(
            model_name='postuserreaction',
            index=models.Index(fields=['owner', 'post', 'unlike'], name='posts_postu_owner_i_95f974_idx'),
        ),
        migrations.AddIndex(
            model_name='postuserreaction',
            index=models.Index(fields=['owner', 'post', 'like', 'unlike'], name='posts_postu_owner_i_3da5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='posts_post_title_e7697c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_post_created_dadbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner', 'created_at'], name='posts_post_owner_i_c6778d_idx'),
        ),
    ]
