# Generated by Django 3.0.7 on 2020-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(null=True, related_name='post_reactions', to='posts.PostUserReaction'),
        ),
    ]
