# Generated by Django 3.0.7 on 2020-06-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200611_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlike',
        ),
        migrations.DeleteModel(
            name='PostUserReaction',
        ),
    ]
