# Generated by Django 3.0.7 on 2020-06-06 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('starnaviapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikeunlike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlikeunlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnaviapp.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentlikeunlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnaviapp.Comment'),
        ),
        migrations.AddField(
            model_name='commentlikeunlike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starnaviapp.Post'),
        ),
        migrations.AddIndex(
            model_name='postlikeunlike',
            index=models.Index(fields=['owner', 'post'], name='starnaviapp_owner_i_384949_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikeunlike',
            index=models.Index(fields=['owner', 'post', 'like'], name='starnaviapp_owner_i_8c68e2_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikeunlike',
            index=models.Index(fields=['owner', 'post', 'unlike'], name='starnaviapp_owner_i_3c84a9_idx'),
        ),
        migrations.AddIndex(
            model_name='postlikeunlike',
            index=models.Index(fields=['owner', 'post', 'like', 'unlike'], name='starnaviapp_owner_i_0a3f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['pub_date'], name='starnaviapp_pub_dat_20a8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['owner', 'pub_date'], name='starnaviapp_owner_i_bd9b84_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlikeunlike',
            index=models.Index(fields=['owner', 'comment'], name='starnaviapp_owner_i_5bf112_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlikeunlike',
            index=models.Index(fields=['owner', 'comment', 'like'], name='starnaviapp_owner_i_a99d26_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlikeunlike',
            index=models.Index(fields=['owner', 'comment', 'unlike'], name='starnaviapp_owner_i_7a88e2_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlikeunlike',
            index=models.Index(fields=['owner', 'comment', 'like', 'unlike'], name='starnaviapp_owner_i_a41c42_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['pub_date'], name='starnaviapp_pub_dat_d32d63_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'pub_date'], name='starnaviapp_owner_i_1c43bc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'post', 'pub_date'], name='starnaviapp_owner_i_b6b224_idx'),
        ),
    ]
