# Generated by Django 3.0.7 on 2020-06-22 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlike_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unlike',
                'verbose_name_plural': 'Unlikes',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AddIndex(
            model_name='unlike',
            index=models.Index(fields=['owner'], name='reactions_u_owner_i_d5206c_idx'),
        ),
        migrations.AddIndex(
            model_name='unlike',
            index=models.Index(fields=['owner', 'unlike_id'], name='reactions_u_owner_i_5c90a9_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['owner'], name='reactions_l_owner_i_71e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['owner', 'like_id'], name='reactions_l_owner_i_29255e_idx'),
        ),
    ]
