# Generated by Django 3.0.7 on 2020-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='reactions_l_owner_i_29255e_idx',
        ),
        migrations.RemoveIndex(
            model_name='unlike',
            name='reactions_u_owner_i_5c90a9_idx',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='unlike',
            old_name='unlike_id',
            new_name='object_id',
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['owner', 'object_id'], name='reactions_l_owner_i_25ab77_idx'),
        ),
        migrations.AddIndex(
            model_name='unlike',
            index=models.Index(fields=['owner', 'object_id'], name='reactions_u_owner_i_eb48b4_idx'),
        ),
    ]
