# Generated by Django 3.0.7 on 2020-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20200622_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Unlike',
        ),
    ]
