# Generated by Django 3.0.7 on 2020-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_auto_20200626_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
