# Generated by Django 3.0.7 on 2020-06-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0004_auto_20200622_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
