# Generated by Django 3.0.7 on 2020-06-11 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_body', models.TextField()),
                ('like', models.PositiveIntegerField(default=0)),
                ('unlike', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentUserReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('unlike', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CommentUserReaction',
                'verbose_name_plural': 'CommentUserReactions',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='reactions',
            field=models.ManyToManyField(related_name='comment_reactions', to='comments.CommentUserReaction'),
        ),
        migrations.AddIndex(
            model_name='commentuserreaction',
            index=models.Index(fields=['owner', 'comment'], name='comments_co_owner_i_1afa68_idx'),
        ),
        migrations.AddIndex(
            model_name='commentuserreaction',
            index=models.Index(fields=['owner', 'comment', 'like'], name='comments_co_owner_i_c452ac_idx'),
        ),
        migrations.AddIndex(
            model_name='commentuserreaction',
            index=models.Index(fields=['owner', 'comment', 'unlike'], name='comments_co_owner_i_5340d8_idx'),
        ),
        migrations.AddIndex(
            model_name='commentuserreaction',
            index=models.Index(fields=['owner', 'comment', 'like', 'unlike'], name='comments_co_owner_i_6a93cb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_co_post_id_380fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comments_co_created_5f6a12_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'created_at'], name='comments_co_owner_i_86b627_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['owner', 'post', 'created_at'], name='comments_co_owner_i_c80390_idx'),
        ),
    ]
