# Generated by Django 3.0.7 on 2020-06-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlike',
        ),
        migrations.DeleteModel(
            name='CommentUserReaction',
        ),
    ]
